image: node:6.9
script:
  - npm install
  - npm install pm2 -g
  - pm2 start server.js
  - npm test
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: drone-ci
    username: drone-ci