image: node:6.9

nodejs_run:
  stage: test
  script:
    - npm install
    - npm install pm2 -g
    - pm2 start server.js --name node-microservice
    - npm test
    - pm2 stop node-microservice

build_image:
  stage: development
  script:
    - docker build -t faisalrahman/nodemicroservice .
